name: interchange-workshop
channels:
  - jaimergp/label/unsupported-cudatoolkit-shim
  - conda-forge
dependencies:
  - python =3.9
  - openff-toolkit >=0.11.0
  - openff-evaluator-base >=0.4.0
  - nglview
  - ipywidgets >7,<8  # https://github.com/nglviewer/nglview/issues/1032
