name: examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.9"

    steps:
    - uses: actions/checkout@v3

    - name: Install conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Environment Information
      run: |
        conda info
        conda list

    - name: Run example notebooks
      if: always()
      run: |
        python -m pytest notebooks/ --nbval-lax
